### ISSUE TITLE
ETV is lost on page refresh

### ISSUE THREAD

**Issue by tolotrasamuel** [FMaz008/VineHelper#130]
**Describe the bug**
ETV is not saved on page refresh

**To Reproduce**
1. Search "CozyEss Birthday Decoration"
2. https://www.amazon.com/vine/vine-items?search=CozyEss%20Birthday%20Decoration
3. ETV has not been reported yet
4. Click "see Details"
5. ETV is reported and displaying correctly on popup close
6. Refresh the page.
7. ETV is lost again

**Expected behavior**
On page refresh, ETV should remain.

**Browser**
Chrome
 
**Additional context**
This happens on almost all ASIN that are parents and has multiple variant. The variant child ETV is reported but instead, the parent is  showing in "Notification Monitoring last 100" 

Suggestion: Show all variants in the "Notification Monitoring last 100"  feature.

**Comment by FMaz008** [comment]
The bug you describe and the "additional context" are 2 separate issues:

For the problem of the ETV not persisting:
That was a problem a few days ago and should be fixed by now. (Make sure to update your extension to the latest version, which right now is 2.9.9)
You account (UUID) also needs to have a certain age to be allowed to contribute data. If you don't meet certain criteria, your ETV won't be saved.

Notification Monitor issues:
- Variants in notification monitor: no, some product have upward of 50+ variants and that would be an absolute mess. The current system will display the parent item, which is found before any variant, and the ETV will be updated when/if found.

- Under the old notification system **of the new API**, products with variants won't get an ETV displayed.
- The new instant notification system is about to get an update and the parent item will have the ETV of the latest variant found.

For reference, the listing should display a range of ETV prices when multiple variants with different prices have been found for a parent item. This is resource intensive on the database and not something I can implement (at the moment) in the notifications.
 
Hope this clarifies a bit.

**Comment by FMaz008** [comment]
I believe this was resolves. If it is still an issue, feel free to reopen
