### ISSUE TITLE
Pinned tab now shows list instead of grid

### ISSUE THREAD

**Issue by 1920x1200** [FMaz008/VineHelper#134]
After getting upgraded to Vine Helper 2.9.6, the "pinned" tab now shows items in a list view instead of previous grid view. 
I do not have list view enabled and can not find any settings specif to this pinned tab. The list view wastes too much space. How can I revert it back to the grid view? 

Firefox 130.0.1, macOS 15.0, Vine Helper 2.9.6

**Comment by FMaz008** [comment]
That's a bit odd but that's normal. The pin list are generated items where as the other items are generated by amazon with their fancy html, which isnthen getting heavilly modified by css and whatnot.

It would be a bit complicated to make them look the same, but I would welcome a PR to make them behave uniformly.

**Comment by FMaz008** [comment]
It wasn't exactly a grid, it was a messy design kind of looking like a grid but it was otherwise unflexible and didn't work that well on mobile. The lack of proper toolbar was one of the issue.

I took the time to give them a proper design which scale well, but doing it "the same as amazon" was a bit too complicated.

I agree it would be better it it was uniform, just didn't the time/motivation to do it yet.

**Comment by 1920x1200** [comment]
The new list view is a big step backwards in my option. The old layout was far superior for desktop use. Please consider adding an option to bring the old layout back.

**Comment by FMaz008** [comment]
Done for the next release. :) It will show a grid view by default and show a list view if the option is selected.

**Comment by FMaz008** [comment]
2.10.4 released.
