### ISSUE TITLE
[Bug]: clicking on VineHelper's Windows notification popup goes to search for "undefined" in Amazon Vine page

### ISSUE THREAD

**Issue by LitBomb** [FMaz008/VineHelper#153]
### Bug Description

clicking on VineHelper's Windows notification popup goes to search for "undefined" in Amazon Vine page

### Steps to Reproduce

1. In Vine Helper's notification tab, turn on "Check for New Items" and "Push Notification when KW match"
2. When a KW is matched, a Windows notification popup appears in the lower right corner on the main monitor
3. clicking on the popup brings you to a new tab in the Microsoft Edge browser at this URL: https://www.amazon.com/vine/vine-items?search=undefined

### Expected Behavior

expect to search for the item mentioned in the notification popup instead of "undefined"

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/1d970aa5-047c-49ac-9fca-2349a08a88c9)

### Browser

Microsoft Edge on Windows 11

### Additional Context

This has been happening for a few builds in the last couple of weeks. Separately I have seen it would automatically open up a few of the exact same "undefined" tabs in Edge, up to 12 tabs one time upon clicking on the notification popup.  Sometimes 3 or 5 tabs.  But the most recent report only started one "undefined" tab.

**Comment by FMaz008** [comment]
Double bug find, wow.

1. So for the main one, it was already accidentally fixed for the upcoming release (or if you run the github code). I guess I got it fixed when I implemented a readable stream for the incoming notifications. Had not realized this was a bug tho. So good catch.

While you wait for the next release, you can activate the experimental option "Search open in See Details modal window" which should work (assuming the item is still available)

2. Regarding the opening multiple tabs part, that one I had not caught and is due to every time a push notification is created, a new listening event for the click was generated. I've adjusted the code to not create a new listener event if there is already one created.

For that I have no temporary solution.

**Comment by LitBomb** [comment]
Thanks for the quick reply.  Glad to hear you have fixed it already.  I will wait for the next release.  Thanks.

**Comment by LitBomb** [comment]
One addition.  If you hover your mouse cursor on top of the notification popup, a tooltip comes up with the same text in the notification box, covering up the text below and a bit distracting.  Let me know if you want a separate issue opened.  Thanks.

![image](https://github.com/user-attachments/assets/e90e257d-1903-4bc4-95a7-f9faf58208c0)

**Comment by FMaz008** [comment]
Unfortunately I don't think I can control how a browser decide to display their notifications...

**Comment by FMaz008** [comment]
2.10.4 released.
