### ISSUE TITLE
[Feature Request]: Delete remote items

### ISSUE THREAD

**Issue by DrBazUK** [FMaz008/VineHelper#160]
### Feature Description

I know that there is the option to factory reset and then change the UUID on other clients to remove them but this risks leaving the server with a load of UUIDs and associated list items that will go stale over time/take up space. Unless you have a process to boot them after X days of non use/client not seen in X days.

The feature would be like the existing "remove local stored items" but would apply to the server items - i.e. a way to reset back to the beginning. This could speed up the processing of new items and not risk missing relisted items that had previously been marked as hide when hunting for the wheat amongst the chaff...

**Comment by FMaz008** [comment]
So to your first paragraph, yes the server has a way to garbage collect unused UUIDs.

If you do a factory reset, you will get a new UUID and start over. Unless you copy your old UUID to reuse it, but then you will be linked back to all your remotely stored items and pinned items, if you had remote storage enabled.

... when the UUID get purged on the server, the content associated wirh it will also be purged (ie: the remote hidden item and remote pinned items will be deleted).

I can see a benefit if you want to preserve your config but otherwise clear the memory from (mainly) hidden items.

I'll see what I can do.

**Comment by FMaz008** [comment]
So basically the button will now prompt you for 2 things:
- Do you want to delete local hidden items?
- Do you want to delete remote hidden items?

This should do it :) Will be available in the next release.
